### ISSUE TITLE
requirements for this library to work?

### ISSUE THREAD

**Issue by carbonadam** [bertmelis/esp32ModbusTCP#15]
I am super new to wanting to work with modbus so really sorry if I am just not getting something.  Is any external hardware requried to talk between 2 esp32s using modbus protocol or can we simply use tx rx ect or other pits to output rs485..somehow im not getting it.  I know its not an issue with the library but would love clarification

**Comment by bertmelis** [comment]
https://en.m.wikipedia.org/wiki/Modbus

Why would you use modbus? There are more appropriate ways to communicate between ESPs. Besides, you would need a master and a slave and this lib only acts as master.

RS485 is an electrical spec which happens to be used oftenly by modbus(RTU).
