### ISSUE TITLE
Is it possible to use this along with the encj28j60 Ethernet module for the esp32? 

### ISSUE THREAD

**Issue by AtharZafeer** [bertmelis/esp32ModbusTCP#19]
So, I am trying to implement a modbus tcp/ip over ethernet using [this encj28j60 module](https://www.sunrom.com/p/enc28j60-module). This uses the vspi bus on the ESP32, working with uipethernet library. is it possible to implement a modbus ip/tcp using this over ethernet? 

[UIPETHERNET library](https://github.com/UIPEthernet/UIPEthernet)

**Comment by bertmelis** [comment]
I'm afraid this is nothing that can be easily done. The API of the mentioned lib in totally different and I presume it implements blocking function calls.
