### ISSUE TITLE
SLAVE implemention ？

### ISSUE THREAD

**Issue by yanzixiang** [bertmelis/esp32ModbusTCP#3]
https://github.com/yanzixiang/ArduinoModbusSlaveAsyncTCP

Do you have Interest to mix this SLAVE implemention  and your esp32ModbusTCP ?

**Comment by bertmelis** [comment]
Always interested. However, I'm reworking this lib as it is not stable yet.

The lib is now built on the assumption that a TCP packet contains the entire modbus message at once. But this is not the case and I regularly suffer broken connections.

So untill I've solved that issue, I'm not going to spend a lot of time implementing new features.
